---

- name: Create bundle directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/bundle"
    state: directory

- name: Install Vundle
  git:
    repo: "git@github.com:VundleVim/Vundle.vim.git"
    dest: "{{ lookup('env', 'HOME') }}/.vim/bundle/Vundle.vim"

- name: Install plugins
  command: vim +PluginInstall +qall

